services:
  workspace:
    container_name: image-builder
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.10
    tty: true
    stdin_open: true
    volumes:
      - .:/code
    working_dir: /code