[tool.poetry]
name = "workspace"
version = "0.1.0"
description = "A playground for python project experiment."
authors = ["liuyuweitarek <liuyuwei.tarek@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python="^3.9"
torch={version="1.12.1+cu116", source="torch"}

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.group.test.dependencies]
pytest = "*"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu116"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
