name: Build Image(liuyuweitarek/pytorch:1.7.1-py3.6-cuda11.0-ubuntu20.04)

env:
  IMAGE_TAG: "liuyuweitarek/pytorch:1.7.1-py3.6-cuda11.0-ubuntu20.04"
  PYTHON_VERSION: "3.6"
  PACKAGE_MANAGEMENT: "pip"
  POETRY_VERSION: "1.8.1"
  TORCH_PACKAGE_NAME: "1.7.1+cu110"
  TORCH_SOURCE_URL: "https://download.pytorch.org/whl/cu110"
  PYPROJECT_FILE_DIR: "./default-workspace"
  DEFAULT_PYPROJECT_FILE: ""
  UBUNTU_VERSION: "20.04"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker_build_pytorch1.7.1-py3.6-cuda11.0-ubuntu20.04.yml
  
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Mock Login DockerHub
        run: |
          echo "Login DockerHub"

      - name: Build docker image
        run: |
          cd image-builder/docker
          if [[ $PACKAGE_MANAGEMENT == 'poetry' ]]; then
              bash build-ubuntu-poetry.sh
          else
              bash build-ubuntu-pip.sh
          fi

      - name: Run Test Cases
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get install cuda-toolkit
          sudo reboot
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
          sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
          && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
          sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
          sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
          sudo apt-get update
          sudo apt-get install -y nvidia-container-toolkit
          sudo nvidia-ctk runtime configure --runtime=docker
          sudo systemctl restart docker
          docker run --rm -v $(pwd)/tests:/default-workspace/tests --name test-container --gpus all liuyuweitarek/pytorch:1.7.1-py3.6-cuda11.0-ubuntu20.04 bash -c "pytest tests"

      - name: Push Docker Image on Success && Record Success
        if: success()
        run: |
          echo "Push Docker Image: liuyuweitarek/pytorch:1.7.1-py3.6-cuda11.0-ubuntu20.04"
          echo "Record Success: liuyuweitarek/pytorch:1.7.1-py3.6-cuda11.0-ubuntu20.04"
      
      - name: Record Failure
        if: failure()
        run: |
          echo "Record Failure: liuyuweitarek/pytorch:1.7.1-py3.6-cuda11.0-ubuntu20.04"
